INSERT INTO products( name, product_id) VALUES ('Lamp', 10);
INSERT INTO products( name, product_id) VALUES ('White Shirt', 11);
INSERT INTO products( name, product_id) VALUES ('Toothbrush', 12);
INSERT INTO products( name, product_id) VALUES ('Xbox', 13);
INSERT INTO products(name, product_id) VALUES ('PS5', 14);
INSERT INTO products( name, product_id) VALUES ('Hairbrush', 15);
INSERT INTO products( name, product_id) VALUES ('Cantu', 16);
INSERT INTO products( name, product_id) VALUES ('Zippo lighter', 17);
INSERT INTO products( name, product_id) VALUES ('Apple Keyboard', 18);
INSERT INTO products( name, product_id) VALUES ('AA batteries', 19  );